/**
 * D3FEND Canvas Preset
 *
 * Cyber attack/defense modeling using MITRE D3FEND ontology.
 * Dark theme with 9 node types and 200+ relationship types.
 */

import type { CanvasPreset } from '../types';

export const d3fendPreset: CanvasPreset = {
  meta: {
    id: 'd3fend',
    name: 'D3FEND Canvas',
    version: '1.0.0',
    description: 'Cyber attack/defense modeling using MITRE D3FEND ontology',
    author: 'v2e',
    createdAt: '2026-02-10T00:00:00Z',
    updatedAt: '2026-02-10T00:00:00Z',
  },

  theme: {
    primary: '#6366f1',
    background: '#0f172a',
    surface: '#1e293b',
    text: '#f8fafc',
    textMuted: '#94a3b8',
    border: '#334155',
    accent: '#8b5cf6',
    success: '#22c55e',
    warning: '#f59e0b',
    error: '#ef4444',
  },

  behavior: {
    snapToGrid: true,
    gridSize: 20,
    autoLayout: false,
    historyLimit: 100,
    autoSaveInterval: 5000,
    enableInference: true,
  },

  nodeTypes: [
    {
      id: 'technique',
      label: 'Technique',
      category: 'D3FEND',
      description: 'A defensive technique from D3FEND',
      icon: 'Shield',
      color: '#22c55e',
      borderColor: '#16a34a',
      backgroundColor: '#14532d',
      defaultWidth: 180,
      defaultHeight: 80,
      d3fendClass: 'DefensiveTechnique',
      properties: [
        { key: 'd3fendId', value: '', type: 'string', required: true },
        { key: 'description', value: '', type: 'string' },
      ],
    },
    {
      id: 'tactic',
      label: 'Tactic',
      category: 'D3FEND',
      description: 'A defensive tactic category',
      icon: 'Target',
      color: '#6366f1',
      borderColor: '#4f46e5',
      backgroundColor: '#312e81',
      defaultWidth: 160,
      defaultHeight: 70,
      d3fendClass: 'DefensiveTactic',
      properties: [
        { key: 'd3fendId', value: '', type: 'string', required: true },
        { key: 'description', value: '', type: 'string' },
      ],
    },
    {
      id: 'attack-technique',
      label: 'Attack Technique',
      category: 'ATT&CK',
      description: 'An adversary technique from ATT&CK',
      icon: 'Sword',
      color: '#ef4444',
      borderColor: '#dc2626',
      backgroundColor: '#7f1d1d',
      defaultWidth: 180,
      defaultHeight: 80,
      properties: [
        { key: 'attackId', value: '', type: 'string', required: true },
        { key: 'tactic', value: '', type: 'string' },
        { key: 'description', value: '', type: 'string' },
      ],
    },
    {
      id: 'attack-tactic',
      label: 'Attack Tactic',
      category: 'ATT&CK',
      description: 'An adversary tactic category',
      icon: 'Crosshair',
      color: '#f59e0b',
      borderColor: '#d97706',
      backgroundColor: '#78350f',
      defaultWidth: 160,
      defaultHeight: 70,
      properties: [
        { key: 'attackId', value: '', type: 'string', required: true },
        { key: 'description', value: '', type: 'string' },
      ],
    },
    {
      id: 'asset',
      label: 'Asset',
      category: 'Infrastructure',
      description: 'An infrastructure asset',
      icon: 'Server',
      color: '#06b6d4',
      borderColor: '#0891b2',
      backgroundColor: '#164e63',
      defaultWidth: 160,
      defaultHeight: 70,
      properties: [
        { key: 'type', value: '', type: 'string' },
        { key: 'ip', value: '', type: 'string' },
        { key: 'hostname', value: '', type: 'string' },
      ],
    },
    {
      id: 'software',
      label: 'Software',
      category: 'Infrastructure',
      description: 'Software or application',
      icon: 'Package',
      color: '#a855f7',
      borderColor: '#9333ea',
      backgroundColor: '#581c87',
      defaultWidth: 160,
      defaultHeight: 70,
      properties: [
        { key: 'name', value: '', type: 'string', required: true },
        { key: 'version', value: '', type: 'string' },
        { key: 'vendor', value: '', type: 'string' },
      ],
    },
    {
      id: 'vulnerability',
      label: 'Vulnerability',
      category: 'Security',
      description: 'A security vulnerability (CVE)',
      icon: 'AlertTriangle',
      color: '#f97316',
      borderColor: '#ea580c',
      backgroundColor: '#7c2d12',
      defaultWidth: 180,
      defaultHeight: 70,
      properties: [
        { key: 'cveId', value: '', type: 'string', required: true },
        { key: 'cvss', value: '', type: 'number' },
        { key: 'severity', value: '', type: 'string' },
      ],
    },
    {
      id: 'weakness',
      label: 'Weakness',
      category: 'Security',
      description: 'A software weakness (CWE)',
      icon: 'Bug',
      color: '#eab308',
      borderColor: '#ca8a04',
      backgroundColor: '#713f12',
      defaultWidth: 160,
      defaultHeight: 70,
      properties: [
        { key: 'cweId', value: '', type: 'string', required: true },
        { key: 'description', value: '', type: 'string' },
      ],
    },
    {
      id: 'group',
      label: 'Group',
      category: 'Threat Intel',
      description: 'Threat actor or intrusion set',
      icon: 'Users',
      color: '#ec4899',
      borderColor: '#db2777',
      backgroundColor: '#831843',
      defaultWidth: 160,
      defaultHeight: 70,
      properties: [
        { key: 'name', value: '', type: 'string', required: true },
        { key: 'aliases', value: '', type: 'string' },
        { key: 'country', value: '', type: 'string' },
      ],
    },
  ],

  relationships: [
    // D3FEND relationships
    {
      id: 'subtechnique-of',
      label: 'subtechnique of',
      sourceTypes: ['technique'],
      targetTypes: ['technique'],
      style: { strokeColor: '#6366f1', strokeWidth: 2, strokeStyle: 'dashed' },
    },
    {
      id: 'tactic-includes',
      label: 'includes',
      sourceTypes: ['tactic'],
      targetTypes: ['technique'],
      style: { strokeColor: '#6366f1', strokeWidth: 2 },
    },
    {
      id: 'mitigates',
      label: 'mitigates',
      sourceTypes: ['technique'],
      targetTypes: ['attack-technique', 'vulnerability', 'weakness'],
      style: { strokeColor: '#22c55e', strokeWidth: 2, animated: true },
    },
    {
      id: 'detects',
      label: 'detects',
      sourceTypes: ['technique'],
      targetTypes: ['attack-technique'],
      style: { strokeColor: '#06b6d4', strokeWidth: 2, animated: true },
    },
    {
      id: 'related-to',
      label: 'related to',
      sourceTypes: ['technique'],
      targetTypes: ['technique', 'tactic'],
      style: { strokeColor: '#94a3b8', strokeWidth: 1, strokeStyle: 'dotted' },
    },
    // ATT&CK relationships
    {
      id: 'uses-technique',
      label: 'uses',
      sourceTypes: ['attack-tactic'],
      targetTypes: ['attack-technique'],
      style: { strokeColor: '#f59e0b', strokeWidth: 2 },
    },
    {
      id: 'subtechnique',
      label: 'subtechnique',
      sourceTypes: ['attack-technique'],
      targetTypes: ['attack-technique'],
      style: { strokeColor: '#ef4444', strokeWidth: 2, strokeStyle: 'dashed' },
    },
    {
      id: 'exploits',
      label: 'exploits',
      sourceTypes: ['attack-technique'],
      targetTypes: ['vulnerability', 'weakness'],
      style: { strokeColor: '#ef4444', strokeWidth: 2, animated: true },
    },
    {
      id: 'targets',
      label: 'targets',
      sourceTypes: ['attack-technique', 'group'],
      targetTypes: ['asset', 'software'],
      style: { strokeColor: '#f97316', strokeWidth: 2 },
    },
    {
      id: 'attributed-to',
      label: 'attributed to',
      sourceTypes: ['attack-technique'],
      targetTypes: ['group'],
      style: { strokeColor: '#ec4899', strokeWidth: 2, strokeStyle: 'dashed' },
    },
    {
      id: 'uses-malware',
      label: 'uses',
      sourceTypes: ['group'],
      targetTypes: ['software'],
      style: { strokeColor: '#a855f7', strokeWidth: 2 },
    },
    // Infrastructure relationships
    {
      id: 'runs-on',
      label: 'runs on',
      sourceTypes: ['software'],
      targetTypes: ['asset'],
      style: { strokeColor: '#06b6d4', strokeWidth: 2 },
    },
    {
      id: 'has-vulnerability',
      label: 'has vulnerability',
      sourceTypes: ['software', 'asset'],
      targetTypes: ['vulnerability'],
      style: { strokeColor: '#f97316', strokeWidth: 2, strokeStyle: 'dashed' },
    },
    {
      id: 'has-weakness',
      label: 'has weakness',
      sourceTypes: ['software'],
      targetTypes: ['weakness'],
      style: { strokeColor: '#eab308', strokeWidth: 2, strokeStyle: 'dashed' },
    },
    {
      id: 'connected-to',
      label: 'connected to',
      sourceTypes: ['asset'],
      targetTypes: ['asset'],
      style: { strokeColor: '#94a3b8', strokeWidth: 1, strokeStyle: 'dotted' },
    },
    // Cross-domain relationships
    {
      id: 'caused-by',
      label: 'caused by',
      sourceTypes: ['vulnerability'],
      targetTypes: ['weakness'],
      style: { strokeColor: '#eab308', strokeWidth: 2 },
    },
    {
      id: 'variant-of',
      label: 'variant of',
      sourceTypes: ['vulnerability'],
      targetTypes: ['vulnerability'],
      style: { strokeColor: '#f97316', strokeWidth: 1, strokeStyle: 'dashed' },
    },
  ],
};

export default d3fendPreset;
