package main

const (
	// Main Logs
	LogMsgAttemptImportATTACK = "Attempting to import ATT&CK data from: %s"
	LogMsgATTACKXLSXNotExist  = "ATT&CK XLSX file does not exist: %s"
	LogMsgFailedImportATTACK  = "Failed to import ATT&CK data from %s: %v"
	LogMsgSuccessImportATTACK = "Successfully imported ATT&CK data from: %s"
	LogMsgNoATTACKXLSXFound   = "No ATT&CK XLSX files found for automatic import"
	LogMsgFailedSetupLogging  = "Failed to setup logging: %v"
	LogMsgFailedOpenDB        = "Failed to open database: %v"
	LogMsgFailedOpenCWEDB     = "Failed to open CWE database: %v"
	LogMsgFailedOpenCAPECDB   = "Failed to open CAPEC database: %v"
	LogMsgFailedOpenATTACKDB  = "Failed to open ATT&CK database: %v"
	LogMsgServiceStarted      = "CVE local service started"

	// CVE Handlers Logs
	LogMsgProcessingSaveCVE          = "Processing SaveCVEByID request - Message ID: %s, Correlation ID: %s"
	LogMsgFailedParseSaveCVEReq      = "Failed to parse SaveCVEByID request - Message ID: %s, Correlation ID: %s, Error: %v"
	LogMsgProcessingSaveCVEFailed    = "Processing SaveCVEByID request failed due to malformed payload - Message ID: %s, Payload: %s"
	LogMsgCVEIDRequired              = "CVE ID is required in SaveCVEByID request - Message ID: %s, Correlation ID: %s"
	LogMsgProcessingSaveCVEFailedID  = "Processing SaveCVEByID request failed: CVE ID missing in payload - Message ID: %s"
	LogMsgFailedSaveCVE              = "Failed to save CVE to database - Message ID: %s, Correlation ID: %s, CVE ID: %s, Error: %v"
	LogMsgProcessingSaveCVEFailedErr = "Processing SaveCVEByID request failed for CVE ID %s - Message ID: %s, Error details: %v"
	LogMsgSuccessSaveCVE             = "Successfully saved CVE to local database - Message ID: %s, Correlation ID: %s, CVE ID: %s"
	LogMsgProcessingSaveCVECompleted = "Processing SaveCVEByID request completed successfully - Message ID: %s, CVE ID: %s"
	LogMsgFailedMarshalSaveCVEResp   = "Failed to marshal SaveCVEByID response - Message ID: %s, Correlation ID: %s, Error: %v"
	LogMsgFailedParseReq             = "Failed to parse request: %v"
	LogMsgProcessingIsCVEFailed      = "Processing IsCVEStoredByID request failed due to malformed payload: %s"
	LogMsgCVEIDRequiredSimple        = "cve_id is required"
	LogMsgProcessingIsCVECompleted   = "Processing IsCVEStoredByID request completed successfully for CVE ID %s, stored: %v"
	LogMsgFailedMarshalResult        = "Failed to marshal result: %v"
	LogMsgProcessingGetCVE           = "Processing GetCVEByID request - Message ID: %s, Correlation ID: %s"
	LogMsgFailedParseGetCVEReq       = "Failed to parse GetCVEByID request - Message ID: %s, Correlation ID: %s, Error: %v"
	LogMsgProcessingGetCVEFailed     = "Processing GetCVEByID request failed due to malformed payload - Message ID: %s, Payload: %s"
	LogMsgCVEIDRequiredGet           = "CVE ID is required in GetCVEByID request - Message ID: %s, Correlation ID: %s"
	LogMsgProcessingGetCVEFailedID   = "Processing GetCVEByID request failed: CVE ID missing in payload - Message ID: %s"
	LogMsgFailedGetCVE               = "Failed to get CVE from database - Message ID: %s, Correlation ID: %s, CVE ID: %s, Error: %v"
	LogMsgProcessingGetCVEFailedErr  = "Processing GetCVEByID request failed for CVE ID %s - Message ID: %s, Error details: %v"
	LogMsgSuccessGetCVE              = "Retrieved CVE from local database - Message ID: %s, Correlation ID: %s, CVE ID: %s"
	LogMsgProcessingGetCVECompleted  = "Processing GetCVEByID request completed successfully - Message ID: %s, CVE ID: %s"
	LogMsgFailedMarshalGetCVEResp    = "Failed to marshal GetCVEByID response - Message ID: %s, Correlation ID: %s, Error: %v"
	LogMsgCVEIDNotFound              = "CVE not found: %v"

	// CWE Handlers Logs
	LogMsgProcessingGetCWEFailed    = "Processing GetCWEByID request failed due to malformed payload: %s"
	LogMsgGetCWEByIDReq             = "GetCWEByID request: cwe_id=%s"
	LogMsgFailedGetCWE              = "Failed to get CWE: %v (cwe_id=%s)"
	LogMsgProcessingGetCWEFailedErr = "Processing GetCWEByID request failed for CWE ID %s: %v"
	LogMsgFoundCWE                  = "Found CWE: %+v"
	LogMsgProcessingGetCWECompleted = "Processing GetCWEByID request completed successfully for CWE ID %s"
	LogMsgFailedMarshalCWE          = "Failed to marshal CWE: %v (cwe_id=%s)"
	LogMsgMarshalledCWE             = "Marshalled CWE JSON: %s"
	LogMsgRPCListCWEsInvoked        = "RPCListCWEs handler invoked with message ID: %s"
	LogMsgProcessingListCWEsFailed  = "Processing ListCWEs request failed due to malformed payload: %s"

	// ATT&CK Handlers Logs
	LogMsgImportATTACKInvoked                  = "RPCImportATTACKs handler invoked"
	LogMsgImportATTACKReceivedPath             = "RPCImportATTACKs received path: %s"
	LogMsgFailedImportATTACKXLSX               = "Failed to import ATT&CK from XLSX: %v (path: %s)"
	LogMsgATTACKImportStatError                = "ATT&CK import file stat error: %v (path: %s)"
	LogMsgGetAttackTechniqueByIDReq            = "GetAttackTechniqueByID request: id=%s"
	LogMsgFailedGetAttackTechnique             = "Failed to get ATT&CK technique: %v (id=%s)"
	LogMsgFailedMarshalAttackTechnique         = "Failed to marshal ATT&CK technique: %v (id=%s)"
	LogMsgGetAttackTacticByIDReq               = "GetAttackTacticByID request: id=%s"
	LogMsgFailedGetAttackTactic                = "Failed to get ATT&CK tactic: %v (id=%s)"
	LogMsgFailedMarshalAttackTactic            = "Failed to marshal ATT&CK tactic: %v (id=%s)"
	LogMsgGetAttackMitigationByIDReq           = "GetAttackMitigationByID request: id=%s"
	LogMsgFailedGetAttackMitigation            = "Failed to get ATT&CK mitigation: %v (id=%s)"
	LogMsgFailedMarshalAttackMitigation        = "Failed to marshal ATT&CK mitigation: %v (id=%s)"
	LogMsgGetAttackSoftwareByIDReq             = "GetAttackSoftwareByID request: id=%s"
	LogMsgFailedGetAttackSoftware              = "Failed to get ATT&CK software: %v (id=%s)"
	LogMsgFailedMarshalAttackSoftware          = "Failed to marshal ATT&CK software: %v (id=%s)"
	LogMsgGetAttackGroupByIDReq                = "GetAttackGroupByID request: id=%s"
	LogMsgFailedGetAttackGroup                 = "Failed to get ATT&CK group: %v (id=%s)"
	LogMsgFailedMarshalAttackGroup             = "Failed to marshal ATT&CK group: %v (id=%s)"
	LogMsgProcessingListAttackTechniques       = "Processing ListAttackTechniques request - Message ID: %s, Correlation ID: %s"
	LogMsgFailedParseListAttackTechniques      = "Failed to parse ListAttackTechniques request - Message ID: %s, Correlation ID: %s, Error: %v"
	LogMsgProcessingListAttackTechniquesFailed = "Processing ListAttackTechniques request failed due to malformed payload - Message ID: %s, Payload: %s"
	LogMsgListAttackTechniquesParams           = "Processing ListAttackTechniques request - Message ID: %s, Correlation ID: %s, Offset: %d, Limit: %d"
	LogMsgFailedListAttackTechniques           = "Failed to list ATT&CK techniques from store - Message ID: %s, Correlation ID: %s, Error: %v"
	LogMsgProcessingListAttackTechniquesError  = "Processing ListAttackTechniques request failed - Message ID: %s, Error details: %v"
	LogMsgMappingAttackTechnique               = "Mapping ATT&CK technique - Message ID: %s, Technique ID: %s"
	LogMsgFailedMarshalListAttackTechniques    = "Failed to marshal ListAttackTechniques response - Message ID: %s, Correlation ID: %s, Error: %v"
	LogMsgSuccessListAttackTechniques          = "Successfully processed ListAttackTechniques request - Message ID: %s, Correlation ID: %s, Returned: %d, Total: %d"
	LogMsgListAttackTacticsInvoked             = "RPCListAttackTactics handler invoked with message ID: %s"
	LogMsgListAttackTacticsParams              = "Listing ATT&CK tactics with offset=%d, limit=%d"
	LogMsgFailedListAttackTactics              = "Failed to list ATT&CK tactics: %v"
	LogMsgFailedMarshalListAttackTactics       = "Failed to marshal ATT&CK tactics list: %v"
	LogMsgListAttackMitigationsInvoked         = "RPCListAttackMitigations handler invoked with message ID: %s"
	LogMsgListAttackMitigationsParams          = "Listing ATT&CK mitigations with offset=%d, limit=%d"
	LogMsgFailedListAttackMitigations          = "Failed to list ATT&CK mitigations: %v"
	LogMsgFailedMarshalListAttackMitigations   = "Failed to marshal ATT&CK mitigations list: %v"
	LogMsgListAttackSoftwareInvoked            = "RPCListAttackSoftware handler invoked with message ID: %s"
	LogMsgListAttackSoftwareParams             = "Listing ATT&CK software with offset=%d, limit=%d"
	LogMsgFailedListAttackSoftware             = "Failed to list ATT&CK software: %v"
	LogMsgFailedMarshalListAttackSoftware      = "Failed to marshal ATT&CK software list: %v"
	LogMsgListAttackGroupsInvoked              = "RPCListAttackGroups handler invoked with message ID: %s"
	LogMsgListAttackGroupsParams               = "Listing ATT&CK groups with offset=%d, limit=%d"
	LogMsgFailedListAttackGroups               = "Failed to list ATT&CK groups: %v"
	LogMsgFailedMarshalListAttackGroups        = "Failed to marshal ATT&CK groups list: %v"
	LogMsgGetAttackImportMetadataInvoked       = "RPCGetAttackImportMetadata handler invoked"
	LogMsgFailedGetAttackImportMetadata        = "Failed to get ATT&CK import metadata: %v"
	LogMsgFailedMarshalAttackImportMetadata    = "Failed to marshal ATT&CK import metadata: %v"
)
